Pronia/Pronia/Areas/Admin/ViewModels/Tag/CreateTagVM.cs
namespace Pronia.Areas.Admin.ViewModels
{
	public class CreateTagVM
	{
		public string Name { get; set; }

	}
}

Pronia/Pronia/Areas/Admin/ViewModels/Tag/UpdateTagVM.cs
namespace Pronia.Areas.Admin.ViewModels
{
	public class UpdateTagVM
	{
		public string Name { get; set; }

	}
}

Pronia/Pronia/Models/Tag.cs
namespace Pronia.Models
{
    public class Tag
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<ProductTag> ProductTags { get; set; }
    }
}

Pronia/Pronia/Areas/Admin/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using Pronia.Areas.Admin.ViewModels;
using Pronia.DAL;
using Pronia.Models;

namespace Pronia.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class TagController : Controller
	{
		private readonly AppDbContext _context;

		public TagController(AppDbContext context)
		{
			_context = context;
		}
		public async Task<IActionResult> Index(int page=1)
		{
			int count=await _context.Tags.CountAsync();
			ViewBag.TotalPage = Math.Ceiling((double)count / 3);
			ViewBag.CurrentPage = page;
			List<Tag> tags = await _context.Tags.Skip((page-1)*3).Take(3).ToListAsync();
			PaginateVM<Tag> paginateVM = new PaginateVM<Tag>
			{
				Items = tags,
				TotalPage=Math.Ceiling((double)count / 3),
				CurrentPage=page
			};
			return View(paginateVM);
		}
		public async Task<IActionResult> Create()
		{
			ViewBag.Tags = await _context.Tags.ToListAsync();
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Create(CreateTagVM tagVM)
		{
			if (!ModelState.IsValid)
			{
				ViewBag.Tags=await _context.Tags.ToListAsync();
				return View();
			}
			bool result = _context.Tags.Any(c => c.Name.Trim() == tagVM.Name.Trim());
			if (!result)
			{
				ViewBag.Tags = await _context.Tags.ToListAsync();
				ModelState.AddModelError("Name", "This name is already available.");
			}
			Tag tag = new Tag()
			{
				Name = tagVM.Name,
			};

			await _context.Tags.AddAsync(tag);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}
		public async Task<IActionResult> Update(int id)
		{
			if (id <= 0) return BadRequest();
          
			Tag existed = await _context.Tags.FirstOrDefaultAsync(t => t.Id== id);
            
			if (existed == null) NotFound();
			UpdateTagVM tagVM = new UpdateTagVM()
			{
				Name = existed.Name,
			};
			return View(tagVM);
		
		}
		[HttpPost]

		public async Task<IActionResult> Update(int id, UpdateTagVM tagVM)
		{
			if(ModelState.IsValid)return View();
			Tag existed=await _context.Tags.FirstOrDefaultAsync(t=>t.Id==id);
			if (existed == null) NotFound();

			bool result=await _context.Tags.AnyAsync(t=>t.Name==tagVM.Name && t.Id==id);
			if (result)
			{
				ViewBag.Tags = await _context.Tags.ToListAsync();
				ModelState.AddModelError("Name", "This category already exist.");
				return View();
			}
			existed.Name = tagVM.Name;
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));

		}
		public async Task<IActionResult> Delete(int id)
		{
			if(id<=0) return BadRequest();
			Tag existed=await _context.Tags.FirstOrDefaultAsync(t=> t.Id==id);
			if (existed == null) NotFound();
			_context.Tags.Remove(existed);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

        public async Task<IActionResult> Detail(int id)
        {
            if (id <= 0) return BadRequest();

            Tag detail = await _context.Tags.FirstOrDefaultAsync(d => d.Id == id);
            if (detail == null) NotFound();



            return View(detail);

        }
    }
}

Pronia/Pronia/Areas/Admin/Views/Tag/Create.cshtml
@model CreateTagVM

<div class="main-panel">
	<div class="content-wrapper">
		<div class="row">

			<div class="col-12 grid-margin stretch-card">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Create Tag</h4>

						<form class="forms-sample" method="post" enctype="multipart/form-data">
							<div class="form-group">
								<label asp-for="Name">Name</label>
								<input asp-for="Name" class="form-control" placeholder="Name">
								<span class="text-danger" asp-validation-for="Name"></span>
							</div>
							<a asp-controller="Tag" asp-action="Create" class="btn btn-success">Create Tag</a>
							<button type="submit" class="btn btn-primary mr-2">Submit</button>
							<button class="btn btn-light">Cancel</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Pronia/Pronia/Areas/Admin/Views/Tag/Detail.cshtml
@model Tag
<div class="row">

    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Name:@Model.Name</h5>
        </div>
        <div class="card-body">
            <a asp-controller="Tag" asp-action="index" class="btn btn-success">Cancel</a>
        </div>
    </div>
</div>

Pronia/Pronia/Areas/Admin/Views/Tag/Index.cshtml
@model PaginateVM<Tag>
@{
	int count = (Model.CurrentPage-1)*3;
}
<div class="main-panel">
	<div class="content-wrapper">
		<div class="row">

			<div class="col-lg-12 grid-margin stretch-card">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Tag Table</h4>
						<a class="btn btn-success">Create Tag</a>
						<div class="table-responsive">
							<table class="table table-striped">
								<thead>
									<tr>
										<th>
											No
										</th>
										<th>
											Name
										</th>
										<th>
											Products Count
										</th>
										<th>
											Settings
										</th>

									</tr>
								</thead>
								<tbody>
									@foreach (Tag tag in Model.Items)
									{
										count++;
										<tr>
											<td>
												@count
											</td>

											<td>
												@tag.Name
											</td>
											
											<td>
												<a class="btn btn-warning btn-info"><i class="mdi mdi-pencil"></i></a>
												<a class="btn btn-danger btn-info"><i class="mdi mdi-delete"></i></a>
												<a class="btn btn-primary"><i class="mdi mdi-open-in-new"></i></a>
											</td>
										</tr>
									}

								</tbody>
							</table>
						</div>
					</div>
					<nav aria-label="Page navigation example">
						<ul class="pagination">
							<li class="page-item @(Model.CurrentPage<=1?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage-1)" asp-action="index" asp-controller="product">Previous</a></li>
							@for (int i = 0; i < Model.TotalPage; i++)
							{
								<li class="page-item @(Model.CurrentPage-1==i? "disabled":"")"><a class="page-link" asp-route-page="@(i+1)" asp-action="index" asp-controller="product">@(i + 1)</a></li>
							}
							<li class="page-item @(Model.TotalPage<=Model.CurrentPage?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage+1)" asp-action="index" asp-controller="product">Next</a></li>
						</ul>
					</nav>
				</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Pronia/Pronia/Areas/Admin/Views/Tag/Update.cshtml
@model UpdateTagVM

<div class="main-panel">
	<div class="content-wrapper">
		<div class="row">

			<div class="col-12 grid-margin stretch-card">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Update Tag</h4>

						<form class="forms-sample" method="post">
							<div class="form-group">
								<label asp-for="Name">Name</label>
								<input asp-for="Name" class="form-control" placeholder="Name">
								<span class="text-danger" asp-validation-for="Name"></span>
							</div>
							<a asp-controller="Tag" asp-action="Update" class="btn btn-success">Update Tag</a>
							<button type="submit" class="btn btn-primary mr-2">Submit</button>
							<button class="btn btn-light">Cancel</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>