Pronia/Pronia/Areas/Admin/ViewModels/Color/CreateColorVM.cs
namespace Pronia.Areas.Admin.ViewModels
{
	public class CreateColorVM
	{
		public string Name { get; set; }
	}
}

Pronia/Pronia/Areas/Admin/ViewModels/Color/UpdateColorVM.cs
namespace Pronia.Areas.Admin.ViewModels.Color
{
	public class UpdateColorVM
	{
		public string Name { get; set; }
	}
}

Pronia/Pronia/Models/Color.cs
namespace Pronia.Models
{
    public class Color
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<ProductColor> ProductColors { get; set; }
    }
}

Pronia/Pronia/Areas/Admin/Controllers/ColorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.Areas.Admin.ViewModels;
using Pronia.DAL;
using Pronia.Models;

namespace Pronia.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class ColorController : Controller
	{

		private readonly AppDbContext _context;

		public ColorController(AppDbContext context)
		{
			_context = context;
		}
		public async Task<IActionResult> Index()
		{
			List<Color> colors = await _context.Colors.ToListAsync();
			return View(colors);
		}
		public async Task<IActionResult> Create()
		{
			ViewBag.Colors = await _context.Colors.ToListAsync();
			return View();
		}
		[HttpPost]
		public async Task<IActionResult> Create(CreateColorVM colorVM)
		{
			if (!ModelState.IsValid)
			{
				ViewBag.Colors = await _context.Colors.ToListAsync();
				return View();
			}
			bool result = _context.Colors.Any(c => c.Name.Trim() == colorVM.Name.Trim());
			if (result)
			{
				ViewBag.Colors = await _context.Colors.ToListAsync();
				ModelState.AddModelError("Name", "This name is already available.");
				return View();
			}
			Color color = new Color()
			{
				Name = colorVM.Name,
			};

			await _context.Colors.AddAsync(color);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));

		}
		public async Task<IActionResult> Update(int id)
		{
			if (id <= 0) return BadRequest();
			Color existed=await _context.Colors.FirstOrDefaultAsync(c => c.Id == id);
			if (existed is null) return NotFound();
			return View(existed);
		}
		[HttpPost]

		public async Task<IActionResult> Update(int id,CreateColorVM colorVM)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}
			Color existed= await _context.Colors.FirstOrDefaultAsync(c=>c.Id==id);
			if (existed is null) return NotFound();

            bool result = await _context.Categories.AnyAsync(c => c.Name == existed.Name && c.Id == id);
            if (result)
            {
				ViewBag.Colors = await _context.Colors.ToListAsync();
				ModelState.AddModelError("Name", "This category already exist.");
                return View();
            }
			existed.Name = colorVM.Name;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();
            Color existed = await _context.Colors.FirstOrDefaultAsync(t => t.Id == id);
            if (existed == null) NotFound();
            _context.Colors.Remove(existed);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Detail(int id)
        {
            if (id <= 0) return BadRequest();

            Color detail = await _context.Colors.FirstOrDefaultAsync(d => d.Id == id);
            if (detail == null) NotFound();


            return View(detail);

        }
    }
}

Pronia/Pronia/Areas/Admin/Views/Color/Create.cshtml
@model CreateColorVM

<div class="main-panel">
	<div class="content-wrapper">
		<div class="row">

			<div class="col-12 grid-margin stretch-card">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Create Color</h4>

						<form class="forms-sample" method="post">
							<div class="form-group">
								<label asp-for="Name">Name</label>
								<input asp-for="Name" class="form-control" placeholder="Name">
								<span class="text-danger" asp-validation-for="Name"></span>
							</div>
							<a asp-controller="Color" asp-action="Create" class="btn btn-success">Create Color</a>
							<button type="submit" class="btn btn-primary mr-2">Submit</button>
							<button class="btn btn-light">Cancel</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Pronia/Pronia/Areas/Admin/Views/Color/Detail.cshtml
@model Color
<div class="row">

    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Name:@Model.Name</h5>
        </div>
        <div class="card-body">
            <a asp-controller="Color" asp-action="index" class="btn btn-success">Cancel</a>
        </div>
    </div>
</div>

Pronia/Pronia/Areas/Admin/Views/Color/Index.cshtml
@model List<Color>
@{
	int count = 0;
}
<div class="main-panel">
	<div class="content-wrapper">
		<div class="row">

			<div class="col-lg-12 grid-margin stretch-card">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Category Table</h4>
						<a class="btn btn-success">Create Category</a>
						<div class="table-responsive">
							<table class="table table-striped">
								<thead>
									<tr>
										<th>
											No
										</th>
										<th>
											Name
										</th>
										<th>
											Products Count
										</th>
										<th>
											Settings
										</th>

									</tr>
								</thead>
								<tbody>
									@foreach (Color color in Model)
									{
										count++;
										<tr>
											<td>
												@count
											</td>

											<td>
												@color.Name
											</td>
											
											<td>
												<a class="btn btn-warning btn-info"><i class="mdi mdi-pencil"></i></a>
												<a class="btn btn-danger btn-info"><i class="mdi mdi-delete"></i></a>
												<a class="btn btn-primary"><i class="mdi mdi-open-in-new"></i></a>
											</td>
										</tr>
									}

								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>