Pronia/Pronia/Areas/Admin/ViewModels/Slide/CreateSlideVM.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Pronia.Areas.Admin.ViewModels
{
    public class CreateSlideVM
    {
        [Required]
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public int Order { get; set; }
        [Required]
        public IFormFile Photo { get; set; }
    }
}

Pronia/Pronia/Areas/Admin/ViewModels/Slide/UpdateSlideVM.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Pronia.Areas.Admin.ViewModels
{
    public class UpdateSlideVM
    {
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int Order { get; set; }
        public IFormFile? Photo { get; set; }
    }
}

Pronia/Pronia/Models/Slide.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Pronia.Models
{
    public class Slide
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int Order { get; set; }
        
    }
}

Pronia/Pronia/Areas/Admin/Controllers/SlideController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.Areas.Admin.ViewModels;
using Pronia.DAL;
using Pronia.Models;
using Pronia.Utilities.Extensions;
using System.Numerics;

namespace Pronia.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class SlideController : Controller
	{
		private readonly AppDbContext _context;
		private readonly IWebHostEnvironment _env;
        public SlideController(AppDbContext context,IWebHostEnvironment env)
        {
            _context = context;
			_env = env;
        }
        public async Task<IActionResult> Index()
		{
			List<Slide> slides=await _context.Slides.ToListAsync();
			return View(slides);
		}
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create(CreateSlideVM slideVM)
		{
			

			if (!ModelState.IsValid)
			{
				return View();
			}
			if (!slideVM.Photo.ValidateType("images/")) 
			{
				ModelState.AddModelError("Photo", "The file type is not compatible.");
				return View();
			}
			if(slideVM.Photo.ValidateSize(2 * 1024))
			{
				ModelState.AddModelError("Photo", "File size should not exceed 2 megabytes.");
				return View();
			}

            string fileName =await slideVM.Photo.CreateFileAsync(_env.WebRootPath, "assets", "images","slider");
			Slide slide = new Slide()
			{
				Image = fileName,
				Title = slideVM.Title,
				SubTitle = slideVM.SubTitle,
				Description = slideVM.Description,
				Order = slideVM.Order,
				
			};
			await _context.AddAsync(slideVM);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}
		public async Task<IActionResult> Update(int id)
		{
			if(id<=0) return BadRequest();
			Slide existed =await _context.Slides.FirstOrDefaultAsync(s => s.Id == id);
			if(existed is null) return NotFound();

			UpdateSlideVM slideVM = new UpdateSlideVM()
			{
				Title = existed.Title,
				SubTitle = existed.SubTitle,
				Description = existed.Description,
				Image = existed.Image,
				Order = existed.Order,
			};
			return View(slideVM);
		}
		[HttpPost]

		public async Task<IActionResult> Update(int id,UpdateSlideVM slideVM)
		{
			
			if(!ModelState.IsValid)
			{
				return View(slideVM);
			}
            Slide existed = await _context.Slides.FirstOrDefaultAsync(s => s.Id == id);
            if (existed is null) return NotFound();
            if (slideVM.Photo is not null)
			{
				if (!slideVM.Photo.ValidateType("images/"))
				{
					ModelState.AddModelError("Photo", "The file type is not compatible.");
					return View(slideVM);
				}
				if (slideVM.Photo.ValidateSize(2 * 1024))
				{
					ModelState.AddModelError("Photo", "File size should not exceed 2 megabytes.");
					return View(slideVM);
				}
				string fileName = await slideVM.Photo.CreateFileAsync(_env.WebRootPath, "assets", "images", "slider");
				existed.Image.DeleteFile(_env.WebRootPath,"assets","images","slider");
				existed.Image = fileName;
			}
			existed.Title = slideVM.Title;
			existed.SubTitle = slideVM.SubTitle;
			existed.Description = slideVM.Description;
			existed.Order = slideVM.Order;
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> Delete(int id)
		{
			if (id <= 0) return BadRequest();
			Slide existed=await _context.Slides.FirstOrDefaultAsync(s=>s.Id==id);
			if(existed == null) return NotFound();

			existed.Image.DeleteFile(_env.WebRootPath,"assets","images","slider");
			_context.Slides.Remove(existed);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}


        public async Task<IActionResult> Detail(int id)
        {
            if (id <= 0) return BadRequest();

            Slide detail = await _context.Slides
				.FirstOrDefaultAsync(s => s.Id == id);
            if (detail == null) NotFound();

            return View(detail);

        }
    }
}

Pronia/Pronia/Areas/Admin/Views/Slide/Create.cshtml
@model CreateSlideVM

<div class="main-panel">
	<div class="content-wrapper">
		<div class="row">

			<div class="col-12 grid-margin stretch-card">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Create Slide</h4>

						<form class="forms-sample" method="post" enctype="multipart/form-data">
							<div class="form-group">
								<label asp-for="Photo">Photo</label>
								<input asp-for="Photo" class="form-control" placeholder="Photo">
								<span class="text-danger" asp-validation-for="Photo"></span>
							</div>
							<div class="form-group">
								<label asp-for="Title">Title</label>
								<input asp-for="Title" class="form-control" placeholder="Title">
								<span class="text-danger" asp-validation-for="Title"></span>
							</div>
							<div class="form-group">
								<label asp-for="SubTitle">SubTitle</label>
								<input asp-for="SubTitle" class="form-control" placeholder="SubTitle">
								<span class="text-danger" asp-validation-for="SubTitle"></span>
							</div>

							<div class="form-group">
								<label asp-for="Order">Order</label>
								<input asp-for="Order" class="form-control" placeholder="Order">
								<span class="text-danger" asp-validation-for="Order"></span>
							</div>
							<div class="form-group">
								<label asp-for="Description">Description</label>
								<input asp-for="Description" class="form-control" placeholder="Description">
								<span class="text-danger" asp-validation-for="Description"></span>
							</div>

							<a asp-controller="Slide" asp-action="Create" class="btn btn-success">Create Slide</a>
							<button type="submit" class="btn btn-primary mr-2">Submit</button>
							<button class="btn btn-light">Cancel</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Pronia/Pronia/Areas/Admin/Views/Slide/Detail.cshtml
@model Slide

		<div class="card" style="width: 18rem;">
			<img src="@Model.Image" class="card-img-top" alt="...">
			<div class="card-body">
				<h5 class="card-title">Title:@Model.Title</h5>
				<h3 class="card-title">SubTitle:@Model.SubTitle</h3>
				<p class="card-text">Description:@Model.Description</p>
			</div>
			<ul class="list-group list-group-flush">
				<li class="list-group-item">Order:@Model.Order</li>

			</ul>
			<div class="card-body">
				<a asp-controller="category" asp-action="index"  class="btn btn-success">Cancel</a>
				
			</div>
		</div>

Pronia/Pronia/Areas/Admin/Views/Slide/Index.cshtml
@model List<Slide>
@{
	int count = 0;
}
<div class="main-panel">
	<div class="content-wrapper">
		<div class="row">

			<div class="col-lg-12 grid-margin stretch-card">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Slide Table</h4>
						<a class="btn btn-success">Create Slide</a>
						<div class="table-responsive">
							<table class="table table-striped">
								<thead>
									<tr>
										<th>
											No
										</th>
										<th>
											Image
										</th>
										<th>
											Title
										</th>
										<th>
											Order
										</th>
										<th>
											Settings
										</th>

									</tr>
								</thead>
								<tbody>
									@foreach (Slide Slide in Model)
									{
										count++;
										<tr>
											<td>
												@count
											</td>

											<td>
												<img style="width:150px;height:150px;" src="~/assets/images/slider/@Slide.Image"/>
											</td>
											<td>
												@Slide.Title
											</td>
											<td>
												@Slide.Order
											</td>
											<td>
												<a asp-action="Update" asp-controller="Slide" asp-route-id="@Slide.Id" class="btn btn-warning btn-info"><i class="mdi mdi-pencil"></i></a>
												<a asp-action="Delete" asp-controller="Slide" asp-route-id="@Slide.Id" class="btn btn-danger btn-info"><i class="mdi mdi-delete"></i></a>
												<a class="btn btn-primary"><i class="mdi mdi-open-in-new"></i></a>
											</td>
										</tr>
									}

								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Pronia/Pronia/Areas/Admin/Views/Slide/Update.cshtml
@model UpdateSlideVM

<div class="main-panel">
	<div class="content-wrapper">
		<div class="row">

			<div class="col-12 grid-margin stretch-card">
				<div class="card">
					<div class="card-body">
						<h4 class="card-title">Create Slide</h4>
						
						<form class="forms-sample" method="post" enctype="multipart/form-data">
							
							<div class="form-group">
								<img src="~/assets/images/slider/@Model.Image"></img>
								<input asp-for="Image" type="hidden" class="form-control" value="@Model.Image" >

							</div>
							<div class="form-group">
								<label asp-for="Title">Title</label>
								<input asp-for="Title" class="form-control" placeholder="Title">
								<span class="text-danger" asp-validation-for="Title"></span>
							</div>
							<div class="form-group">
								<label asp-for="SubTitle">SubTitle</label>
								<input asp-for="SubTitle" class="form-control" placeholder="SubTitle">
								<span class="text-danger" asp-validation-for="SubTitle"></span>
							</div>

							<div class="form-group">
								<label asp-for="Order">Order</label>
								<input asp-for="Order" class="form-control" placeholder="Order">
								<span class="text-danger" asp-validation-for="Order"></span>
							</div>
							<div class="form-group">
								<label asp-for="Description">Description</label>
								<input asp-for="Description" class="form-control" placeholder="Description">
								<span class="text-danger" asp-validation-for="Description"></span>
							</div>
							
							<a asp-controller="Slide" asp-action="Create" class="btn btn-success">Create Slide</a>
							<button type="submit" class="btn btn-primary mr-2">Submit</button>
							<button class="btn btn-light">Cancel</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>